# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(898, 1011)
        self.t1f = QtWidgets.QPushButton(Form)
        self.t1f.setGeometry(QtCore.QRect(10, 60, 131, 25))
        self.t1f.setObjectName("t1f")
        self.chicken = QtWidgets.QPushButton(Form)
        self.chicken.setGeometry(QtCore.QRect(40, 230, 101, 25))
        self.chicken.setObjectName("chicken")
        self.egg = QtWidgets.QPushButton(Form)
        self.egg.setGeometry(QtCore.QRect(40, 270, 101, 25))
        self.egg.setObjectName("egg")
        self.pizza = QtWidgets.QPushButton(Form)
        self.pizza.setGeometry(QtCore.QRect(40, 310, 101, 25))
        self.pizza.setObjectName("pizza")
        self.orange = QtWidgets.QPushButton(Form)
        self.orange.setGeometry(QtCore.QRect(40, 350, 101, 25))
        self.orange.setObjectName("orange")
        self.lemon = QtWidgets.QPushButton(Form)
        self.lemon.setGeometry(QtCore.QRect(40, 390, 101, 25))
        self.lemon.setObjectName("lemon")
        self.peach = QtWidgets.QPushButton(Form)
        self.peach.setGeometry(QtCore.QRect(40, 430, 101, 25))
        self.peach.setObjectName("peach")
        self.applejuice = QtWidgets.QPushButton(Form)
        self.applejuice.setGeometry(QtCore.QRect(40, 470, 101, 25))
        self.applejuice.setObjectName("applejuice")
        self.orangejuice = QtWidgets.QPushButton(Form)
        self.orangejuice.setGeometry(QtCore.QRect(40, 510, 101, 25))
        self.orangejuice.setObjectName("orangejuice")
        self.tomatojuice = QtWidgets.QPushButton(Form)
        self.tomatojuice.setGeometry(QtCore.QRect(40, 550, 101, 25))
        self.tomatojuice.setObjectName("tomatojuice")
        self.order = QtWidgets.QPushButton(Form)
        self.order.setGeometry(QtCore.QRect(290, 350, 121, 101))
        self.order.setObjectName("order")
        self.table2 = QtWidgets.QPushButton(Form)
        self.table2.setGeometry(QtCore.QRect(170, 370, 90, 60))
        self.table2.setObjectName("table2")
        self.table3 = QtWidgets.QPushButton(Form)
        self.table3.setGeometry(QtCore.QRect(170, 490, 90, 60))
        self.table3.setObjectName("table3")
        self.table1 = QtWidgets.QPushButton(Form)
        self.table1.setGeometry(QtCore.QRect(170, 250, 90, 60))
        self.table1.setObjectName("table1")
        self.t2f = QtWidgets.QPushButton(Form)
        self.t2f.setGeometry(QtCore.QRect(160, 60, 131, 25))
        self.t2f.setObjectName("t2f")
        self.t3f = QtWidgets.QPushButton(Form)
        self.t3f.setGeometry(QtCore.QRect(310, 60, 131, 25))
        self.t3f.setObjectName("t3f")
        self.t1b = QtWidgets.QPushButton(Form)
        self.t1b.setGeometry(QtCore.QRect(460, 60, 131, 25))
        self.t1b.setObjectName("t1b")
        self.t2b = QtWidgets.QPushButton(Form)
        self.t2b.setGeometry(QtCore.QRect(610, 60, 131, 25))
        self.t2b.setObjectName("t2b")
        self.t3b = QtWidgets.QPushButton(Form)
        self.t3b.setGeometry(QtCore.QRect(760, 60, 131, 25))
        self.t3b.setObjectName("t3b")
        self.k1b = QtWidgets.QPushButton(Form)
        self.k1b.setGeometry(QtCore.QRect(460, 110, 131, 25))
        self.k1b.setObjectName("k1b")
        self.k2b = QtWidgets.QPushButton(Form)
        self.k2b.setGeometry(QtCore.QRect(610, 110, 131, 25))
        self.k2b.setObjectName("k2b")
        self.k1f = QtWidgets.QPushButton(Form)
        self.k1f.setGeometry(QtCore.QRect(10, 110, 131, 25))
        self.k1f.setObjectName("k1f")
        self.k2f = QtWidgets.QPushButton(Form)
        self.k2f.setGeometry(QtCore.QRect(160, 110, 131, 25))
        self.k2f.setObjectName("k2f")
        self.k3f = QtWidgets.QPushButton(Form)
        self.k3f.setGeometry(QtCore.QRect(310, 110, 131, 25))
        self.k3f.setObjectName("k3f")
        self.k3b = QtWidgets.QPushButton(Form)
        self.k3b.setGeometry(QtCore.QRect(760, 110, 131, 25))
        self.k3b.setObjectName("k3b")
        self.stop = QtWidgets.QPushButton(Form)
        self.stop.setGeometry(QtCore.QRect(760, 10, 131, 41))
        self.stop.setObjectName("stop")
        self.k3d = QtWidgets.QPushButton(Form)
        self.k3d.setGeometry(QtCore.QRect(610, 20, 131, 25))
        self.k3d.setObjectName("k3d")
        self.k2d = QtWidgets.QPushButton(Form)
        self.k2d.setGeometry(QtCore.QRect(460, 20, 131, 25))
        self.k2d.setObjectName("k2d")
        self.k1d = QtWidgets.QPushButton(Form)
        self.k1d.setGeometry(QtCore.QRect(310, 20, 131, 25))
        self.k1d.setObjectName("k1d")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 180, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 140, 881, 20))
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 590, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(470, 180, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(470, 810, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.selectedfood = QtWidgets.QLabel(Form)
        self.selectedfood.setGeometry(QtCore.QRect(30, 660, 421, 341))
        self.selectedfood.setWordWrap(True)
        self.selectedfood.setObjectName("selectedfood")
        self.orderededfood = QtWidgets.QLabel(Form)
        self.orderededfood.setGeometry(QtCore.QRect(470, 230, 421, 551))
        self.orderededfood.setWordWrap(True)
        self.orderededfood.setObjectName("orderededfood")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.t1f.setText(_translate("Form", "Table 1 Front"))
        self.chicken.setText(_translate("Form", "Chicken"))
        self.egg.setText(_translate("Form", "Egg"))
        self.pizza.setText(_translate("Form", "Donut"))
        self.orange.setText(_translate("Form", "Orange"))
        self.lemon.setText(_translate("Form", "Lemon"))
        self.peach.setText(_translate("Form", "Peach"))
        self.applejuice.setText(_translate("Form", "Apple Juice"))
        self.orangejuice.setText(_translate("Form", "Orange Juice"))
        self.tomatojuice.setText(_translate("Form", "Tomato Juice"))
        self.order.setText(_translate("Form", "Place Order"))
        self.table2.setText(_translate("Form", "Table 2"))
        self.table3.setText(_translate("Form", "Table 3"))
        self.table1.setText(_translate("Form", "Table 1"))
        self.t2f.setText(_translate("Form", "Table 2 Front"))
        self.t3f.setText(_translate("Form", "Table 3 Front"))
        self.t1b.setText(_translate("Form", "Table 1 Back"))
        self.t2b.setText(_translate("Form", "Table 2 Back"))
        self.t3b.setText(_translate("Form", "Table 3 Back"))
        self.k1b.setText(_translate("Form", "Kitchen 1 Back"))
        self.k2b.setText(_translate("Form", "Kitchen 2 Back"))
        self.k1f.setText(_translate("Form", "Kitchen 1 Front"))
        self.k2f.setText(_translate("Form", "Kitchen 2 Front"))
        self.k3f.setText(_translate("Form", "Kitchen 3 Front"))
        self.k3b.setText(_translate("Form", "Kitchen 3 Back"))
        self.stop.setText(_translate("Form", "Stop"))
        self.k3d.setText(_translate("Form", "Kitchen 3 Door"))
        self.k2d.setText(_translate("Form", "Kitchen 2 Door"))
        self.k1d.setText(_translate("Form", "Kitchen 1 Door"))
        self.lineEdit.setText(_translate("Form", " Robot Control"))
        self.lineEdit_2.setText(_translate("Form", "Order Food"))
        self.label.setText(_translate("Form", "____________________________________________________________________________________________________________________________________"))
        self.lineEdit_3.setText(_translate("Form", "Selected Food"))
        self.lineEdit_4.setText(_translate("Form", "Order Status"))
        self.lineEdit_5.setText(_translate("Form", "Delivered"))
        self.selectedfood.setText(_translate("Form", "Abc"))
        self.orderededfood.setText(_translate("Form", "Abc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

